# Site settings
author: Uma Manandhar
title: MY FIRST BLOG EVER...
header-img: img/home-bg.png
email: um_2003_8@hotmail.com
copyright_name: Uma Manandhar
description: > # this means to ignore newlines until "baseurl:"
  First experience on writing blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mdr-uma

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
